version: '3'
services:
  www:
    image: edgarjimenez/apache_mysqli
    volumes: 
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=id20342822_bd22313_alzh_edg
      - MYSQL_ROOT_PASSWORD=Passwert
      - MYSQL_USER=php_shuckso
      - MYSQL_PASSWORD=pepega123
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST = db
      - PMA_PORT = 3306
